BEGIN;
-- password is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
-- password : password
-- users
INSERT INTO users(email, enabled, first_name, last_name, password) VALUES ('test@test.com',true, 'Tomasz','Nowak','$2a$04$LUCZ9Co/YSdhrG.nXs2pZO.R1FgkE21xz6VDWbsEPeKI7ehqTMlsS');
INSERT INTO users(email, enabled, first_name, last_name, password) VALUES ('test2@test.com',true, 'Anna','Kowal','$2a$04$LUCZ9Co/YSdhrG.nXs2pZO.R1FgkE21xz6VDWbsEPeKI7ehqTMlsS');

COMMIT;