
-- trigger to update rating in user table, H2 db not allow create triggers that way
-- if db will be changed delete setting it in java code and create trigger in mysql

-- CREATE OR REPLACE TRIGGER RATING_UPDATE
-- AFTER INSERT, UPDATE
-- ON USER_RATING
-- FOR EACH ROW
-- BEGIN
--   UPDATE USERS
--   SET RATING = (SELECT AVG(UR.RATING)
--                 FROM USER_RATING UR
--                 WHERE RELATED_USER_ID = :NEW.RATED_USER_ID)
--   WHERE ID = :NEW.RATED_USER_ID
-- END;

BEGIN;

-- password is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
-- password : password
-- users
INSERT INTO users(email, enabled, first_name, last_name, password, rating) VALUES ('test@test.com',true, 'Tomasz','Nowak','$2a$04$LUCZ9Co/YSdhrG.nXs2pZO.R1FgkE21xz6VDWbsEPeKI7ehqTMlsS', '0');
INSERT INTO users(email, enabled, first_name, last_name, password, rating) VALUES ('test2@test.com',true, 'Anna','Kowal','$2a$04$LUCZ9Co/YSdhrG.nXs2pZO.R1FgkE21xz6VDWbsEPeKI7ehqTMlsS', '0');

COMMIT;