CREATE OR REPLACE FUNCTION update_user_avg_rating()
  RETURNS trigger AS
  $BODY$
  BEGIN
    UPDATE USERS
    SET RATING = (SELECT AVG(UR.RATING)
                FROM USER_RATING UR
                WHERE UR.RATED_USER_ID = NEW.RATED_USER_ID)
    WHERE ID = NEW.RATED_USER_ID;
    RETURN NULL;
  END;
  $BODY$

LANGUAGE plpgsql VOLATILE;


CREATE  TRIGGER RATING_UPDATE
AFTER INSERT OR UPDATE ON USER_RATING
FOR EACH ROW
EXECUTE PROCEDURE update_user_avg_rating();