spring:
    profiles: prod
login: ${ENV_EMAIL}
password: ${ENV_EMAIL_PASS}
replyTo: ${ENV_REPLY_TO}
setFrom: ${ENV_SEND_FROM}
appURL: ${ENV_APP_URL}

---

spring:
    profiles: dev
login: /////
password: ///
replyTo: /////
setFrom: /////
appURL: http://localhost:8080